name: ‚ñ∂Ô∏è Backup-epg-grabber

on:
  schedule:
    # Runs every 8 hours at 00:00, 08:00, 16:00 UTC
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  epg-grabber:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run epg grabber
        run: cd Backup && python Backup-epg-grabber.py

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add epgs/Backup-epg.xml epgs/Backup-epg.xml.gz
          git diff --staged --quiet || git commit -m "üîÑ Update epg"
          git push --force
