name: TV5 IPTV EPG Auto Builder

on:
  schedule:
    - cron: "5 21 * * *"   # 04:05 sáng giờ VN
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py

      - name: Commit EPG
        run: |
          git config user.name "tv5-epg-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/epg.xml
          git commit -m "Update EPG" || echo "No changes"
          git push
